info:
    image: alxsap/mta-build-deploy
    script:
        - 'pwd'
        - 'whoami'
        - 'ls -la'
        - 'mta.sh || true'
        - 'neo.sh || true'

mtabuild:
    image: alxsap/mta-build-deploy
    script:
      - sed -e 's/webshop/webshopgitlab/g' -i mta.yaml
      - export PATH=./node_modules/.bin:${PATH}
      - mta.sh --mtar result.mtar --build-target=NEO build

neodeploy:
    image: alxsap/mta-build-deploy
    dependencies:
        - mtabuild
    script:
      - neo.sh deploy-mta --host "${{NEO_DEPLOY_HOST}}" --account "${{NEO_DEPLOY_ACCOUNT}}" --synchronous --user "${{NEO_DEPLOY_USER}}" --password "${{NEO_DEPLOY_PASSWORD}}" --source "result.mtar"
      - echo "Application running at https://webshopcodefresh-${{NEO_DEPLOY_ACCOUNT}}.dispatcher.${{NEO_DEPLOY_HOST}}/index.html"
