stages:
    - build
    - deploy

info:
    image: alxsap/mta-build-deploy
    stage: build
    script:
        - 'pwd'
        - 'whoami'
        - 'ls -la'
        - 'mta.sh || true'
        - 'neo.sh || true'

mtabuild:
    image: alxsap/mta-build-deploy
    stage: build
    script:
      - 'ls -la'
      - sed -e 's/webshop/webshopgitlab/g' -i mta.yaml
      - export PATH=./node_modules/.bin:${PATH}
      - mta.sh --mtar result.mtar --build-target=NEO build
      - 'ls -la'
    artifacts:
        name: mtabuild
        paths:
          - result.mtar
          - package-lock.json

neodeploy:
    image: alxsap/mta-build-deploy
    stage: deploy
    dependencies:
        - mtabuild
    script:
      - 'ls -la'
      - neo.sh deploy-mta --host "${NEO_DEPLOY_HOST}" --account "${NEO_DEPLOY_ACCOUNT}" --synchronous --user "${NEO_DEPLOY_USER}" --password "${NEO_DEPLOY_PASSWORD}" --source "result.mtar"
      - echo "Application running at https://webshopgitlab-${NEO_DEPLOY_ACCOUNT}.dispatcher.${NEO_DEPLOY_HOST}/index.html"
      - 'ls -la'
    artifacts:
        name: deploylogs
        untracked: true
        when: always
        expire_in: 1 week

info2:
    image: alxsap/mta-build-deploy
    stage: deploy
    script:
        - 'pwd'
        - 'whoami'
        - 'ls -la'
        - 'cd ..'
        - 'pwd'
        - 'ls -la'
        - 'cd ..'
        - 'pwd'
        - 'ls -la'
