mtabuild:
    image: alxsap/mta-build-deploy
    stage: build
    script:
      - sed -e 's/webshop/webshopgitlab/g' -i mta.yaml
      - export PATH=./node_modules/.bin:${PATH}
      - mta.sh --mtar result.mtar --build-target=NEO build
    artifacts:
        paths:
          - result.mtar

neodeploy:
    image: alxsap/mta-build-deploy
    stage: deploy
    dependencies:
        - mtabuild
    script:
      - neo.sh deploy-mta --host "${NEO_DEPLOY_HOST}" --account "${NEO_DEPLOY_ACCOUNT}" --synchronous --user "${NEO_DEPLOY_USER}" --password "${NEO_DEPLOY_PASSWORD}" --source "result.mtar"
      - echo "Application running at https://webshopgitlab-${NEO_DEPLOY_ACCOUNT}.dispatcher.${NEO_DEPLOY_HOST}/index.html"

cfdeploy:
    image: alxsap/mta-build-deploy
    stage: deploy
    dependencies:
        - mtabuild
    script:
      - cf login -a "${CF_ENDPOINT}" -u "${CF_USER}" -p "${CF_PASSWORD}" -o "${CF_ORG}" -s "${CF_SPACE}"
      - cf deploy result.mtar
      - echo "Application running at ..."
