build_mta:
    image: alxsap/mta-build-deploy
    stage: build
    script:
      - sed -e 's/webshop/webshopgitlab/g' -i mta.yaml
      - sed -e 's/espm/espmgitlab/g' -i mta.yaml
      - export PATH=./node_modules/.bin:${PATH}
      - mta.sh --mtar result.mtar --build-target=CF build
    artifacts:
        paths:
          - result.mtar

deploy_cf
    image: alxsap/mta-build-deploy:v2
    stage: deploy
    dependencies:
        - build_mta
    script:
      - cf --version
      - cf login -a "${CF_ENDPOINT}" -u "${CF_USER}" -p "${CF_PASSWORD}" -o "${CF_ORG}" -s "${CF_SPACE}"
      - cf deploy result.mtar -f -t 30
      - echo "Application running at ..."
